apiVersion: v1
kind: Service
metadata:
  name: studio
  namespace: chronos-dev
spec:
  selector:
    app: studio
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio
  namespace: chronos-dev
  labels:
    app: studio
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: studio
  template:
    metadata:
      labels:
        app: studio
    spec:
      containers:
        - name: studio
          image: registry.docker.tld/studio:latest
          ports:
            - containerPort: 80
      restartPolicy: Always
      imagePullSecrets:
        - name: container-registry