name: Build and deploy
on:
  push:
    branches: [ master, development ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.REGISTRY_URL }}/chronos-studio
  DOCKER_FILE: docker/Dockerfile
  K8S_CLUSTER_NAME: chronos-cloud
  K8S_RG: ChronosCloud
  K8S_NAMESPACE_DEV: chronos-dev
  K8S_NAMESPACE_PRODUCTION: chronos-production
  K8S_DEPLOYMENT_APP: studio

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    outputs:
      version: ${{ steps.version.outputs.newTag }}
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: 16
      - name: "Bump version"
        id: version
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build-development:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' }}
    strategy:
      matrix:
        include:
          - image_tag: ${{ github.sha }}
            api_base_url: https://wss.dev.domain.tld/api
            wss_base_url: wss://wss.dev.domain.tld
    steps:
      - uses: actions/checkout@v3
      - name: Login into ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up docker context for buildx
        run: docker context create builder
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builder
      - name: Build and push docker containers
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VITE_API_BASE_URL=${{ matrix.api_base_url }}
            VITE_WSS_BASE_URL=${{ matrix.wss_base_url }}
          context: ${{ env.GITHUB_WORKSPACE }}
          file:  ${{ env.DOCKER_FILE }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}

  build-production:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    strategy:
      matrix:
        include:
          - image_tag: ${{ needs.bump-version.outputs.version }}
            api_base_url: https://wss.domain.tld/api
            wss_base_url: wss://wss.domain.tld
          - image_tag: ${{ needs.bump-version.outputs.version }}-bm
            api_base_url: https://wss.chronosai.local/api
            wss_base_url: wss://wss.chronosai.local
    needs: [bump-version]
    steps:
      - uses: actions/checkout@v3
      - name: Login into ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up docker context for buildx
        run: docker context create builder
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builder
      - name: Build and push docker containers
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VITE_API_BASE_URL=${{ matrix.api_base_url }}
            VITE_WSS_BASE_URL=${{ matrix.wss_base_url }}
          context: ${{ env.GITHUB_WORKSPACE }}
          file:  ${{ env.DOCKER_FILE }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}

  deploy-development:
    needs: build-development
    if: ${{ github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v2.0
      - name: Login into AKS
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.K8S_CLUSTER_NAME }}
          resource-group: ${{ env.K8S_RG }}
      - name: Deploy
        run: |
          kubectl set image deployment.apps/${{ env.K8S_DEPLOYMENT_APP }} ${{ env.K8S_DEPLOYMENT_APP }}=${{ env.IMAGE_NAME }}:${{ github.sha }} --record --namespace=${{ env.K8S_NAMESPACE_DEV }}
          kubectl rollout restart deployment.apps/${{ env.K8S_DEPLOYMENT_APP }} --namespace=${{ env.K8S_NAMESPACE_DEV }}

  deploy-production:
    needs: [bump-version, build-production]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: azure/setup-kubectl@v2.0
      - name: Login into AKS
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.K8S_CLUSTER_NAME }}
          resource-group: ${{ env.K8S_RG }}
      - name: Deploy
        run: |
          kubectl set image deployment.apps/${{ env.K8S_DEPLOYMENT_APP }} ${{ env.K8S_DEPLOYMENT_APP }}=${{ env.IMAGE_NAME }}:${{ needs.bump-version.outputs.version }} --record --namespace=${{ env.K8S_NAMESPACE_PRODUCTION }}
          kubectl rollout restart deployment.apps/${{ env.K8S_DEPLOYMENT_APP }} --namespace=${{ env.K8S_NAMESPACE_PRODUCTION }}